import {SlashCommandBuilder,PermissionFlagsBits,ChannelType} from 'discord.js';
const s=new SlashCommandBuilder;
const user=(b,n='user')=>b.addUserOption(o=>o.setName(n).setDescription('Member').setRequired(true));
const reason=b=>b.addStringOption(o=>o.setName('reason').setDescription('Reason').setMaxLength(500));
export const commands=[
 s.setName('kick').setDescription('Kick a member').setDefaultMemberPermissions(PermissionFlagsBits.KickMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 s.setName('ban').setDescription('Ban a member').setDefaultMemberPermissions(PermissionFlagsBits.BanMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 s.setName('unban').setDescription('Unban by user ID').setDefaultMemberPermissions(PermissionFlagsBits.BanMembers).addStringOption(o=>o.setName('user_id').setDescription('ID').setRequired(true)),
 s.setName('timeout').setDescription('Timeout a member').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('duration').setDescription('Examples: 10m, 2h, 1d').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 s.setName('untimeout').setDescription('Remove timeout').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)),
 s.setName('warn').setDescription('Warn a member').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(true)),
 s.setName('warnings').setDescription('View warnings').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)),
 s.setName('clear').setDescription('Delete recent messages').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addIntegerOption(o=>o.setName('amount').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)),
 s.setName('slowmode').setDescription('Set channel slowmode').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels).addIntegerOption(o=>o.setName('duration').setDescription('Seconds, 0 disables').setMinValue(0).setMaxValue(21600).setRequired(true)),
 s.setName('embed').setDescription('Send an embed').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addStringOption(o=>o.setName('description').setDescription('Body').setRequired(true)).addStringOption(o=>o.setName('title').setDescription('Title')).addStringOption(o=>o.setName('color').setDescription('Hex color, e.g. #5865F2')).addChannelOption(o=>o.setName('channel').setDescription('Destination').addChannelTypes(ChannelType.GuildText)),
 s.setName('serverinfo').setDescription('Show server information'),s.setName('userinfo').setDescription('Show user information').addUserOption(o=>o.setName('user').setDescription('User')),
 s.setName('avatar').setDescription('Show avatar').addUserOption(o=>o.setName('user').setDescription('User')),
 s.setName('ping').setDescription('Check latency'),s.setName('uptime').setDescription('Show uptime'),s.setName('botinfo').setDescription('Show bot information'),s.setName('help').setDescription('List commands'),
 s.setName('lock').setDescription('Lock this channel').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels),s.setName('unlock').setDescription('Unlock this channel').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels),
 s.setName('announce').setDescription('Send an announcement').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addStringOption(o=>o.setName('message').setDescription('Announcement').setRequired(true)).addChannelOption(o=>o.setName('channel').setDescription('Destination').addChannelTypes(ChannelType.GuildText)),
 s.setName('say').setDescription('Send a message').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addStringOption(o=>o.setName('message').setDescription('Message').setRequired(true)),
 s.setName('poll').setDescription('Create a poll').addStringOption(o=>o.setName('question').setDescription('Question').setRequired(true)),
 s.setName('nick').setDescription('Change nickname').setDefaultMemberPermissions(PermissionFlagsBits.ManageNicknames).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('nickname').setDescription('New nickname').setMaxLength(32)),
 s.setName('setup').setDescription('Configure logging and protection').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('setting').setDescription('Setting').setRequired(true).addChoices({name:'log channel',value:'log_channel'},{name:'anti-link on',value:'anti_link'},{name:'anti-spam on',value:'anti_spam'},{name:'anti-nuke on',value:'anti_nuke'})).addChannelOption(o=>o.setName('channel').setDescription('Channel for log channel setting').addChannelTypes(ChannelType.GuildText)),
 s.setName('config').setDescription('View server configuration').setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
 new SlashCommandBuilder().setName('webhook').setDescription('Manage webhooks').setDefaultMemberPermissions(PermissionFlagsBits.ManageWebhooks).addSubcommand(x=>x.setName('list').setDescription('List webhooks')).addSubcommand(x=>x.setName('info').setDescription('Show webhook info').addStringOption(o=>o.setName('id').setDescription('Webhook ID').setRequired(true))).addSubcommand(x=>x.setName('delete').setDescription('Delete a webhook').addStringOption(o=>o.setName('id').setDescription('Webhook ID').setRequired(true))).addSubcommand(x=>x.setName('create').setDescription('Create a webhook').addStringOption(o=>o.setName('name').setDescription('Name').setRequired(true)).addChannelOption(o=>o.setName('channel').setDescription('Channel').addChannelTypes(ChannelType.GuildText).setRequired(true)))
].map(x=>x.toJSON());
